# .gitlab-ci.yml (for GitLab CI)
# or
# .github/workflows/main.yml (for GitHub Actions)
# or
# azure-pipelines.yml (for Azure Pipelines)

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my-container-image
  TAG: latest

build:
  stage: build
  script:
    - echo "Building the container..."
    - docker build -t $IMAGE_NAME:$TAG .

test:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here

deploy:
  stage: deploy
  script:
    - echo "Pushing the container to a container registry..."
    - docker push $IMAGE_NAME:$TAG
    - echo "Deploying the container to Kubernetes..."
    - kubectl apply -f path/to/your/kubernetes/deployment.yaml
